version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "80:80"
    container_name: admin-dashboard-frontend
    restart: unless-stopped
    
    # Optional: Add environment variables if needed
    # environment:
    #   - NODE_ENV=production
    
    # Optional: Add volume for nginx logs
    volumes:
      - nginx-logs:/var/log/nginx
    
    # Optional: Add health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  nginx-logs: 